name: Run regression tests
on: [pull_request]
jobs:
  regressions:
    runs-on: macos-latest
    steps:
      - name: ğŸ“¦ Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn

      - name: ğŸ— Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # - name: Install Xcode
      #  uses: maxim-lobanov/setup-xcode@v1
      #  with:
      #    xcode-version: latest

      - name: Run tests
        run: |
          # curl -Ls "https://get.maestro.mobile.dev" | bash
          # export PATH="$PATH":"$HOME/.maestro/bin"
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          expo client:install:ios --latest
          xcrun simctl openurl booted "exp://exp.host/@lukoapp/sandbox?release-channel=pr-16"
          yarn sandbox:test:visual --verbose
          yarn sandbox:test:visual:compare

      # yarn sandbox:start --ios &
